### ISSUE TITLE
Archive Request

### ISSUE THREAD

**Issue by blockarchitech** [znci/dev-docs#3]
This repository will be archived on Friday, April 7th, 2023 because it is marked as useless.

**Comment by blockarchitech** [comment]
Docs will eventually be discontinued in the favor of our notion site

**Comment by TheUnium** [comment]
no, docs will be moved to docs.znci.dev and hosted on the vps.

**Comment by blockarchitech** [comment]
Archive Request fulfilled as there was no point to keep this open.
